[package]
name = "gate-pipeline"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.104"
host = { version = "0.1.0", path = "../host" }
tempfile = "3.27.0"
wasmtime = { version = "48", default-features = false, features = ["runtime", "cranelift", "anyhow"] }
wasmtime-wasi = { version = "48", default-features = false, features = ["p1"] }
